services:
  vllm-gemma4-downloader:
    build:
      context: ./downloader
      dockerfile: Dockerfile
    profiles:
      - downloader
    container_name: vllm-gemma4-downloader
    volumes:
      - ./models:/models
      - ./downloader/main.py:/app/main.py
    restart: 'no'

  vllm-gemma:
    profiles:
      - live
      - vllm
    image: docker.io/vllm/vllm-openai:latest
    container_name: vllm-gemma
    runtime: nvidia
    environment:
      HF_TOKEN: ${HF_TOKEN}
    devices:
      - "nvidia.com/gpu=all"
    volumes:
      - ./CACHE:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: >
      --model Qwen/Qwen3-0.6B

   # restart: unless-stopped

  crewai-app:
    profiles:
      - live
    build: ./crewai-app
    container_name: crewai-app
    #restart: unless-stopped
    environment:
      OPENAI_API_KEY: "local"   # dummy, not used
      OPENAI_BASE_URL: "http://vllm-gemma:8000/v1"
      OPENAI_MODEL_NAME: "gemma4"
      DATASET_ROOT: "/datasets"
    depends_on:
      - vllm-gemma
    volumes:
      - ./datasets:/datasets:ro

  open-webui:
    profiles:
      - live
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    depends_on:
      - vllm-gemma
    environment:
      OLLAMA_BASE_URL: ""                 # disable Ollama
      OPENAI_API_BASE_URL: "http://vllm-gemma:8000/v1"
      OPENAI_API_KEY: "local"            # dummy key
      WEBUI_AUTH: "true"                 # enable multi-user login
      WEBUI_SESSION_MODE: "per-user"     # isolate sessions
      WEBUI_CLEANUP_INACTIVE_SESSIONS: "true"
    volumes:
      - webui-data:/app/backend/data
    ports:
      - "3000:8080"
    #restart: unless-stopped

volumes:
  webui-data:
    driver: local
    name: webui-data

  cache_huggingface:
    driver: local
    name: cache_huggingface

# source https://docs.vllm.ai/en/stable/deployment/docker/#pre-built-images
# source https://podman-desktop.io/docs/podman/gpu
# source https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-yum-or-dnf
# source https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html
    
    #   ollama run deepseek-r1
    #   ollama run deepseek-r1:1.5b
    #   ollama run bramvanroy/fietje-2b-chat:Q3_K_M
    #   ollama run jobautomation/OpenEuroLLM-Dutch
    #   ollama run gemma4:e4b-it-q4_K_M