services:
  vllm:
    profiles:
      - live
      - vllm
    image: docker.io/vllm/vllm-openai:latest
    container_name: vllm
    runtime: nvidia
    environment:
      HF_TOKEN: ${HF_TOKEN}
    devices:
      - "nvidia.com/gpu=all"
    volumes:
      - ./CACHE:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    command: google/gemma-3-4b-it #--port 8000 --max-num-seqs 512 --max-parallel-requests 256 # --max-model-len 32768 --gpu-memory-utilization 0.90 --enable-auto-batching true

   # restart: unless-stopped

  crewai-app:
    profiles:
      - live
    build: ./crewai-app
    container_name: crewai-app
    #restart: unless-stopped
    environment:
      OPENAI_API_KEY: "local"   # dummy, not used
      OPENAI_BASE_URL: "http://vllm:8000/v1"
      OPENAI_MODEL_NAME: "gemma4"
      DATASET_ROOT: "/datasets"
    depends_on:
      - vllm
    volumes:
      - ./datasets:/datasets:ro

  open-webui:
    profiles:
      - live
      - open-webui
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    environment:
      OLLAMA_BASE_URL: ""                 # disable Ollama
      OPENAI_API_BASE_URL: "http://vllm:8000/v1"
      OPENAI_API_KEY: "local"            # dummy key
      WEBUI_AUTH: "true"                 # enable multi-user login
      WEBUI_SESSION_MODE: "per-user"     # isolate sessions
      WEBUI_CLEANUP_INACTIVE_SESSIONS: "true"
    volumes:
      - webui-data:/app/backend/data
    ports:
      - "3000:8080"
    #restart: unless-stopped
    entrypoint: tail -f anything  # keep container running, webui will start automatically
 

    
      # VLLM_MODEL: "/models/gemma4"
      # VLLM_MAX_MODEL_LEN: "32768"          # larger context = better multi-session isolation
      # VLLM_GPU_MEMORY_UTILIZATION: "0.90"  # maximize KV cache space
      # VLLM_ENABLE_AUTO_BATCHING: "true"    # continuous batching
      # VLLM_MAX_NUM_SEQS: "512"             # number of parallel sequences
      # VLLM_MAX_PARALLEL_REQUESTS: "256"    # simultaneous requests allowed
      # NVIDIA_VISIBLE_DEVICES: "all"
      # NVIDIA_DRIVER_CAPABILITIES: "compute,utility"

volumes:
  open-webui:
    driver: local
    name: open-webui
  webui-data:
    driver: local
    name: webui-data
  cache_huggingface:
    driver: local
    name: cache_huggingface

# source https://docs.vllm.ai/en/latest/deployment/frameworks/open-webui/
# source https://docs.vllm.ai/en/stable/deployment/docker/#pre-built-images
# source https://podman-desktop.io/docs/podman/gpu
# source https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-yum-or-dnf
# source https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html
    
    #   ollama run deepseek-r1
    #   ollama run deepseek-r1:1.5b
    #   ollama run bramvanroy/fietje-2b-chat:Q3_K_M
    #   ollama run jobautomation/OpenEuroLLM-Dutch
    #   ollama run gemma4:e4b-it-q4_K_M